/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
// package gui;

// /**
//  *
//  * @author jamesmcnellylisette
//  */
// public class LandingPage extends javax.swing.JPanel {

//     /**
//      * Creates new form LandingPage
//      */
//     public LandingPage() {
//         initComponents();
//     }

//     /**
//      * This method is called from within the constructor to initialize the form.
//      * WARNING: Do NOT modify this code. The content of this method is always
//      * regenerated by the Form Editor.
//      */
//     @SuppressWarnings("unchecked")
//     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//     private void initComponents() {

//         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
//         this.setLayout(layout);
//         layout.setHorizontalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGap(0, 400, Short.MAX_VALUE)
//         );
//         layout.setVerticalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGap(0, 300, Short.MAX_VALUE)
//         );
//     }// </editor-fold>//GEN-END:initComponents


//     // Variables declaration - do not modify//GEN-BEGIN:variables
//     // End of variables declaration//GEN-END:variables
// }

package gui;

import com.mycompany.apu_oodj_afs.core.LoginManager;
import com.mycompany.apu_oodj_afs.models.User;
import javax.swing.JOptionPane;

/**
 *
 * @author jamesmcnellylisette
 */
public class LandingPage extends javax.swing.JPanel {

    public LandingPage() {
        initComponents();
    }

    @SuppressWarnings("unchecked")
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        lblTitle.setText("APU Assessment Feedback System");
        lblUsername.setText("Username:");
        lblPassword.setText("Password:");

        btnLogin.setText("Login");
        btnLogin.addActionListener(evt -> btnLoginActionPerformed());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);

        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(lblTitle)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblUsername)
                        .addComponent(lblPassword))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtUsername, 150, 150, 150)
                        .addComponent(txtPassword, 150, 150, 150)))
                .addComponent(btnLogin)
        );

        layout.setVerticalGroup(
            layout.createSequentialGroup()
                .addGap(30)
                .addComponent(lblTitle)
                .addGap(20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername))
                .addGap(10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword))
                .addGap(20)
                .addComponent(btnLogin)
        );
    }

    private void btnLoginActionPerformed() {

        String username = txtUsername.getText().trim();
        String password = new String(txtPassword.getPassword());

        User user = LoginManager.authenticate(username, password);

        if (user == null) {
            JOptionPane.showMessageDialog(
                this,
                "Invalid username or password",
                "Login Failed",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        JOptionPane.showMessageDialog(
            this,
            "Welcome " + user.getName() + " (" + user.getRole() + ")",
            "Login Successful",
            JOptionPane.INFORMATION_MESSAGE
        );

        // IMPORTANT:
        // Do NOT open dashboards yet if they are not implemented
        // user.displayDashboard();
    }

    // Variables declaration
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JButton btnLogin;
}

